services:
  svelte:
    container_name: svelte
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BROWSER_PORT: "9001"
    volumes:
      - minio-data:/data
    command: server /data --address ":9000" --console-address ":9001"

volumes:
  minio-data: